name: CI

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "poetry"

      - run: poetry install

      - name: Build wheels
        run: poetry build

      - name: Upload wheels
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wheels
          path: dist
