name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run task test

  coverage:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "poetry"
      - run: poetry install
      - name: Run pytest-cov
        run: poetry run pytest tests/ --cov=ffmpegwithpy --cov-report=xml:coverage.xml --cov-branch
      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@v1.1.37
        with:
          pytest-xml-coverage-path: ./coverage.xml
