name: Lint

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "poetry"

      - name: Install poetry
        run: pipx install poetry

      - run: poetry install

      - name: Run lint
        run: poetry run task lint
